import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types src/types/appwrite.ts`.

export enum OrganizationType {
    ADVISOR = "advisor",
    CLIENT = "client"
}

export enum OrganizationStatus {
    ACTIVE = "active",
    INACTIVE = "inactive"
}

export enum TenantStatus {
    ACTIVE = "active",
    INACTIVE = "inactive",
    SUSPENDED = "suspended"
}

export enum UserRole {
    OWNER = "owner",
    ADVISOR = "advisor",
    CLIENT_ADMIN = "client_admin",
    CLIENT_EMPLOYEE = "client_employee"
}

export enum UserStatus {
    ACTIVE = "active",
    INACTIVE = "inactive",
    PENDING = "pending"
}

export enum ChecklistStatus {
    DRAFT = "draft",
    ACTIVE = "active",
    COMPLETED = "completed",
    ARCHIVED = "archived"
}

export enum ChecklistItemStatus {
    RED = "red",
    YELLOW = "yellow",
    GREEN = "green"
}

export enum Action {
    LOGIN = "login",
    LOGOUT = "logout",
    DOCUMENT_UPLOAD = "document_upload",
    DOCUMENT_DOWNLOAD = "document_download",
    DOCUMENT_DELETE = "document_delete",
    CHECKLIST_CREATE = "checklist_create",
    CHECKLIST_UPDATE = "checklist_update",
    CHECKLIST_DELETE = "checklist_delete",
    USER_CREATE = "user_create",
    USER_UPDATE = "user_update",
    USER_DELETE = "user_delete",
    DATA_EXPORT = "data_export",
    DATA_DELETE = "data_delete"
}

export type Organizations = Models.Document & {
    tenant_id: string;
    type: OrganizationType;
    name: string;
    tax_id: string | null;
    contact_email: string;
    contact_phone: string | null;
    status: OrganizationStatus;
}

export type Tenants = Models.Document & {
    team_id: string;
    subdomain: string;
    name: string;
    owner_email: string;
    branding_logo_url: string | null;
    branding_primary_color: string | null;
    branding_secondary_color: string | null;
    status: TenantStatus;
}

export type Users = Models.Document & {
    tenant_id: string;
    organization_id: string;
    appwrite_user_id: string;
    role: UserRole;
    first_name: string;
    last_name: string;
    email: string;
    phone: string | null;
    status: UserStatus;
    last_login_at: string | null;
}

export type Checklists = Models.Document & {
    tenant_id: string;
    organization_id: string;
    title: string;
    description: string | null;
    total_items: number;
    completed_items: number;
    status: ChecklistStatus;
    due_date: string | null;
}

export type ChecklistItems = Models.Document & {
    checklist_id: string;
    title: string;
    description: string | null;
    status: ChecklistItemStatus;
    position: number;
    requires_document: boolean;
}

export type Documents = Models.Document & {
    tenant_id: string;
    checklist_item_id: string | null;
    storage_file_id: string;
    filename: string;
    mime_type: string;
    file_size: number;
    uploaded_by_user_id: string;
}

export type AuditLogs = Models.Document & {
    tenant_id: string;
    organization_id: string | null;
    user_id: string;
    action: Action;
    resource_type: string | null;
    resource_id: string | null;
    details: string | null;
    ip_address: string | null;
}
